# Generated by Django 5.0.7 on 2024-08-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
